# This is an example of platform description file

# "na": not-applicable (use default value)
# "unknown": unknown feature (use default value)
# "unset": feature not set (calculate it from the database)
# "ignore": the feature is being ignored (use default value)

[node]

node_count = 1
node_provider = "OnPremise"
node_virtual = "No"
node_dedicated = "Yes"  
node_machinefamily = "na"  
node_machinetype = "na"
node_machinesize = "na"
node_vcpus_count = "na"

[processor]

processor = "unset"
processor_count = 1
processor_manufacturer = "unset"
processor_microarchitecture = "unset"
processor_simd = "unset"
processor_isa = "unset"
processor_tdp = "unset"    # W
processor_core_clock = "unset"
processor_core_count = 1
processor_core_threads_count = 1
processor_core_L1_size = "unset"
processor_core_L2_size = "unset"
processor_L3_size = "unset"

[accelerator]

accelerator = "unset"
accelerator_count = 0
accelerator_type = "unset"
accelerator_manufacturer = "unset"
accelerator_api = "unset"
accelerator_architecture = "unset"
accelerator_memory_size = "unset"
accelerator_tdp = "unset"   # W
accelerator_processor = "unset"
accelerator_processor_count = "unset"

[memory]

node_memory_type = "unset"
node_memory_frequency = "unset"
node_memory_size = "unset"
node_memory_latency = "unset"
node_memory_bandwidth =  "unset"

[storage]

storage_type = "unset"
storage_interface = "unset"
storage_size = "unset"
storage_latency = "unset"  
storage_bandwidth = "unset"
storage_networkbandwidth = "unset"

[interconnection]

interconnection_startuptime = "unset"
interconnection_latency = "unset"
interconnection_bandwidth = "unset"
interconnection_topology = "unset"
interconnection_RDMA = "unset"
interconnection = "unset"

