name = "PlatformAware"
uuid = "e7c50b67-2c03-471e-9cf2-69e515d86ecf"
authors = ["Francisco Heron de Carvalho Junior <heron@dc.ufc.br> and contributors"]
version = "0.1.0"

[deps]
Decimals = "abce61dc-4473-55a0-ba07-351d65e31d42"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[compat]
XMLDict = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
